### ISSUE TITLE
failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by longway2go** [liuchong/docker-nginx-htpasswd#2]
首先，十分感谢您分享的开源项目。
我在运行容器后，后台报错。报错内容如下：
`2019/01/04 02:29:50 [error] 16#16: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 1.81.77.239, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://0.0.0.0:3006/favicon.ico", host: "33.124.121.25:3006", referrer: "http://33.124.121.25:3006/"`
我运行容器的命令如下：

`docker run -p 3006:80 --name test-nginx -v $PWD:/usr/share/nginx/html -d docker.io/liuchong/nginx-htpasswd start -u amdin -p admin -P 80 -X 33.124.121.25:3006`

我怀疑是proxy_pass或者nginx的监听端口号有问题导致的。还请您不吝赐教，指点一下我。

**Comment by liuchong** [comment]
```
docker run -p 3006:80 --name test-nginx -v $PWD:/usr/share/nginx/html -d 
```
是不是上一步的命令，就是上面那行，没执行成功？或者监听的host不对，比如改成0.0.0.0之类的？

**Comment by longway2go** [comment]
@liuchong 感谢回答，应该和上一步的指令无关，或许我需要把nginx好好学习下，然后再学习下你的代码，方能找到答案。
关于上一步的命令，是生成并运行一个test-nginx的容器，其内部端口号为80，对外暴露端口号为3006。该容器镜像来源于你的nginx-htpasswd，且指定了用户名、密码、服务端口号和代理地址。
我主要是不明白start脚本中的服务端口号和代理地址(proxy_pass)，具体是做什么用的。我怀疑是我这里配置错误导致的问题。

**Comment by liuchong** [comment]
@longway2go 哦不好意思我没仔细看错了

你看一下这个文件`https://github.com/liuchong/docker-nginx-htpasswd/blob/master/nginx.conf`，这是一个模板，start脚本根据提供的参数把相应的字段替换成真实的，`-P`就是`__LISTEN__`，`-X`就是`__PROXY_PASS__`

我自己试了一下你的命令，就改了下最后面的-X参数，是可以的。是不是你运行这条命令的机器，访问不了你要代理的ip？
另外我看到你的用户名是`amdin`，不是拼错了吧？

这个工具的想法就是配置一个基础认证的nginx把请求转发到一个地址，然后提供一个shell脚本来在启动前更改配置。可能当时考虑的比较简单，有什么不合适的地方，你可以fork一份改一下 :joy_cat:
